/**
 * Prints the SQL that registers The Peacock in Peregrine's database: the venue,
 * its four sections, every table (with Jenny's Resos seat ranges and
 * priorities) and her joined-table combinations, straight from
 * `src/booking/data/venue.ts`. Needs the 20261007 joined-tables migration.
 *
 *   npm run peregrine:seed > <PeregrinePartners repo>/supabase/seed/peacock.sql
 *
 * venue.ts is the one place the floor plan is written. Re-run this after moving
 * or renumbering a table so the console's plan and the website's agree; the
 * statements upsert, so running them twice is harmless.
 */
import { combinations, fixtures, plants, room, stairs, tables, walls, zones } from "../src/booking/data/venue.ts";
import { site } from "../src/lib/site.ts";

/** Fixed, so the website's PEREGRINE_VENUE_ID never changes under it. */
export const PEACOCK_VENUE_ID = "fb19b599-8b90-4576-b84a-1ff0f4eb1f7e";

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);

const out = [];
out.push("-- Generated by peacock-south-yarra/scripts/peregrine-seed.mjs. Do not edit by hand.");
out.push(
  `insert into public.venues (id, slug, name, timezone, website_url, booking_url, phone) values (${q(PEACOCK_VENUE_ID)}, 'the-peacock', ${q(site.name)}, 'Australia/Melbourne', 'https://thepeacock.com.au', 'https://thepeacock.com.au/book-a-table', ${q(site.phone)})`,
  "  on conflict (id) do update set name = excluded.name, website_url = excluded.website_url, booking_url = excluded.booking_url, phone = excluded.phone;",
);
// The room around the tables, so the console's floor plan reads like Jenny's
// drawing: section outlines, walls, back of house, counters, stairs, trees.
// Venue metres, the same axes as the tables. Needs the 20261008 plan migration.
const r3 = (n) => +n.toFixed(3);
const plan = {
  width: room.width,
  depth: room.depth,
  zones: zones.map((z) => ({ id: z.id, name: z.name, open: z.open, outline: z.outline, label: z.labelAt })),
  walls: walls.map((w) => ({ kind: w.kind, from: w.from, to: w.to })),
  fixtures: fixtures.map((f) => ({ kind: f.kind, label: f.label, x: f.x, y: f.y, w: f.w, d: f.d })),
  stairs: { x0: stairs.x0, x1: stairs.x1, y0: stairs.y0, y1: stairs.y1, treads: stairs.treads },
  trees: plants.filter((p) => p.kind === "tree" || p.kind === "fern").map((p) => ({ x: p.x, y: p.y, r: r3(p.size / 2) })),
};
out.push(`update public.venues set plan = ${q(JSON.stringify(plan))}::jsonb where id = ${q(PEACOCK_VENUE_ID)};`);
zones.forEach((z, i) => {
  out.push(
    `insert into public.sections (venue_id, id, name, sort, indoor) values (${q(PEACOCK_VENUE_ID)}, ${q(z.id)}, ${q(z.name)}, ${i}, ${!z.open})`,
    "  on conflict (venue_id, id) do update set name = excluded.name, sort = excluded.sort, indoor = excluded.indoor;",
  );
});
for (const t of tables) {
  out.push(
    `insert into public.venue_tables (venue_id, id, label, section_id, seats, seats_min, priority, shape, x, y, w, d, rot) values (${q(PEACOCK_VENUE_ID)}, ${q(t.id)}, ${q(t.label)}, ${q(t.zone)}, ${t.seats}, ${t.min}, ${t.priority}, ${q(t.shape)}, ${t.x}, ${t.y}, ${t.w}, ${t.d}, ${t.rot})`,
    "  on conflict (venue_id, id) do update set label = excluded.label, section_id = excluded.section_id, seats = excluded.seats, seats_min = excluded.seats_min, priority = excluded.priority, shape = excluded.shape, x = excluded.x, y = excluded.y, w = excluded.w, d = excluded.d, rot = excluded.rot, active = true;",
  );
}
out.push(
  `update public.venue_tables set active = false where venue_id = ${q(PEACOCK_VENUE_ID)} and id not in (${tables.map((t) => q(t.id)).join(", ")});`,
);
// Jenny's joined tables. Rewritten whole each run: a combination is its tables.
out.push(`delete from public.table_combinations where venue_id = ${q(PEACOCK_VENUE_ID)};`);
for (const c of combinations) {
  out.push(
    `insert into public.table_combinations (venue_id, id, table_ids, seats_min, seats_max, priority) values (${q(PEACOCK_VENUE_ID)}, ${q(c.tables.join("+"))}, array[${c.tables.map(q).join(", ")}], ${c.min}, ${c.max}, ${c.priority});`,
  );
}
console.log(out.join("\n"));
