/**
 * Prints the SQL that registers The Peacock in Peregrine's database: the venue,
 * its four sections and every table, straight from `src/booking/data/venue.ts`.
 *
 *   npm run peregrine:seed > ../../../../peregrine-console/supabase/seed/peacock.sql
 *
 * venue.ts is the one place the floor plan is written. Re-run this after moving
 * or renumbering a table so the console's plan and the website's agree; the
 * statements upsert, so running them twice is harmless.
 */
import { tables, zones } from "../src/booking/data/venue.ts";
import { site } from "../src/lib/site.ts";

/** Fixed, so the website's PEREGRINE_VENUE_ID never changes under it. */
export const PEACOCK_VENUE_ID = "fb19b599-8b90-4576-b84a-1ff0f4eb1f7e";

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);

const out = [];
out.push("-- Generated by peacock-south-yarra/scripts/peregrine-seed.mjs. Do not edit by hand.");
out.push(
  `insert into public.venues (id, slug, name, timezone, website_url, booking_url, phone) values (${q(PEACOCK_VENUE_ID)}, 'the-peacock', ${q(site.name)}, 'Australia/Melbourne', 'https://thepeacock.com.au', 'https://thepeacock.com.au/book-a-table', ${q(site.phone)})`,
  "  on conflict (id) do update set name = excluded.name, website_url = excluded.website_url, booking_url = excluded.booking_url, phone = excluded.phone;",
);
zones.forEach((z, i) => {
  out.push(
    `insert into public.sections (venue_id, id, name, sort, indoor) values (${q(PEACOCK_VENUE_ID)}, ${q(z.id)}, ${q(z.name)}, ${i}, ${!z.open})`,
    "  on conflict (venue_id, id) do update set name = excluded.name, sort = excluded.sort, indoor = excluded.indoor;",
  );
});
for (const t of tables) {
  out.push(
    `insert into public.venue_tables (venue_id, id, label, section_id, seats, shape, x, y, w, d, rot) values (${q(PEACOCK_VENUE_ID)}, ${q(t.id)}, ${q(t.label)}, ${q(t.zone)}, ${t.seats}, ${q(t.shape)}, ${t.x}, ${t.y}, ${t.w}, ${t.d}, ${t.rot})`,
    "  on conflict (venue_id, id) do update set label = excluded.label, section_id = excluded.section_id, seats = excluded.seats, shape = excluded.shape, x = excluded.x, y = excluded.y, w = excluded.w, d = excluded.d, rot = excluded.rot, active = true;",
  );
}
out.push(
  `update public.venue_tables set active = false where venue_id = ${q(PEACOCK_VENUE_ID)} and id not in (${tables.map((t) => q(t.id)).join(", ")});`,
);
console.log(out.join("\n"));
